### ISSUE TITLE
Windows nightly crashes/closes immediately

### ISSUE THREAD

**Issue by tech-ticks** [tech-ticks/DreamNexus#81]
https://discord.com/channels/886045133311729684/897884651341877258/897884654340816897

Could not be reproduced on any dev machines

**Comment by evandixon** [comment]
#80 did not fix it. Tag 0.1.1 works though.

**Comment by evandixon** [comment]
https://github.com/tech-ticks/DreamNexus/tree/what-if/remove-rich-presense did not fix it, so it is not directly related to discord rich presense (the most notable change introduced since 0.1.1).

**Comment by evandixon** [comment]
Should be fixed by https://github.com/tech-ticks/DreamNexus/commit/0354fb51b2d766bdcbee07f7527507de1e112de7, but we have to confirm.
